### ISSUE TITLE
After I have run one dials run, I cannot run a second - it keeps the settings from the first run...

### ISSUE THREAD

**Issue by graeme-winter** [ccp4/DUI#1]
Seems the DUI records everything in dials.state - removing this allows me to process a fresh data set.

**Comment by luisodls** [comment]
This is done by iDIALS internally, try running iDIALS from CLI and you will see the same file, same behaviour.

Actually yo can switch between iDIALS and DUI, as long as you exit one before entering another. Each one should pick up where the other left. dials.state is where both save "state"

**Comment by jmp1985** [comment]
I guess we need some way of allowing people to choose whether to pick up old state if they run in the same directory.

How about, if DUI sees a state file, it loads a popup saying "Would you like to recover the previous session?" Or something of that nature.


________________________________

**Comment by graeme-winter** [comment]
** this **

**Comment by graeme-winter** [comment]
Possibly easier - if I go to "import" once I have run some data through, move dials.state to dials.state.$timestamp (say) and make a new dials.state => if I import it is obvious I want to start a new set yes? Or file->new if you want to be completely explicit about it (not a bad idea)

**Comment by jmp1985** [comment]
You could do it this way; however, something that is currently missing from DUI that you can do in idials is to import multiple datasets.

I think you can set the name of the state file in idials, so you could just instantiate idials with the filename dials.state.${timestamp}  and then just have a file->load or file->open or something in the DUI so that you never recover by default but make the user choose to recover their previous processing state.

________________________________

**Comment by luisodls** [comment]
Done, It now asks what to do ... and as per user request it can keep as many old state files as needed.
