### ISSUE TITLE
Make refine-bravais table colours easier to read (+for colourblind)

### ISSUE THREAD

**Issue by ndevenish** [ccp4/DUI#36]
As well as the whole red/green issue we discussed the red is very intense and makes it hard to read. When we discussed this, we talked about possibly making it a more muted/desaturated red And this is what I meant:

![image](https://user-images.githubusercontent.com/529963/28206281-279a6834-687d-11e7-9fb0-6c6a0915232b.png)
Which is higher contrast and easier to see the N, even without the colours. Perhaps do the same thing for the green.

Other options include patterns but without the low-contrast conflict between text and background the letter might be enough.

**Comment by dagewa** [comment]
For example, simply changing [this line](https://github.com/ccp4/DUI/blob/master/mini_idials_w_GUI/dynamic_reindex_gui.py#L272):
```
                    item.setBackground(Qt.red)
```
to
```
                    item.setBackground(QColor(255, 0, 0, 127))
```
produces this result, pretty similar to @ndevenish's example:

![example](https://user-images.githubusercontent.com/11502083/43405309-77adcabc-9411-11e8-9d67-5e379fda0392.png)

It would be better to specify a set of DUI colours rather than instantiating each time, of course, but essentially this is a trivial fix! Adding to high priority now because it is a year old but is easy.
