### ISSUE TITLE
Rename "reindex" button

### ISSUE THREAD

**Issue by rjgildea** [ccp4/DUI#56]
The button between "index" and "refine" is currently named "reindex" which I think is potentially confusing. The most important thing about this step is not the reindexing, but the determination of the bravais/lattice symmetry. The labelling of this button should somehow emphasise this.

**Comment by rjgildea** [comment]
Perhaps the "reindex" tab should be removed altogether, and simply automatically run RBS and reindex immediately after indexing in P1 (if space_group has not been set)?

**Comment by dagewa** [comment]
I think always running RBS automatically after indexing makes sense. Then the lattice table becomes the result of indexing. Further steps can be greyed out until a choice is made. If space_group was set then the choice is automatic, but it is still useful to have run RBS so that later the user can go back and pick a different option for another branch of processing.

**Comment by dagewa** [comment]
Closing as the button is now renamed, but running RBS automatically is still in discussion
