### ISSUE TITLE
Slow navigation between nodes in the history tree 

### ISSUE THREAD

**Issue by jpt000** [ccp4/DUI#8]
When clicking between two finished jobs on the same history tree it takes too long to update results (due to 'Updating Image/Reflections Data' at each time).

**Comment by dagewa** [comment]
We have discussed ways of caching the data for each step so that it does not have to be recalculated each time. When this gets large, it could be written to pickle on disk. Reloading this would still probably be much faster than recalculating

**Comment by dagewa** [comment]
@luisodls I think in principle this should be quite simple, so I've added it to the high priority milestone to clear out of the way quickly. Let me know if you disagree

**Comment by dagewa** [comment]
@luisodls I experimented with dumping and loading the `img_lst` to and from pickle in the `list_p_arrange` function. For the 540 images of the BAG training data the pickle files were 158M in size! Loading these from disk was not faster than recalculating.

I wonder if the information in the `img_lst` object could be represented in a more efficient way.

**Comment by dagewa** [comment]
Further note, for the BAG training data the average number of items per image contained in `img_lst` is 4146, so that's over 4000 lists with data like this:  `[549.1198681180956, 1117.3487933415615, 3, 2, '(-4, 10, 57)']`, for each of 540 images. The 158M figure makes sense, if each of those lists takes about 70 bytes of memory, and there's approx 540*4200 of them!

Why is so much data stored? Partly because for every image DUI stores the predictions that are on that image but also predictions that are on preceding and subsequent N images. We could certainly reduce size by not storing the Miller index string, just the numbers and calculate the string on the fly. However, I think it would be better to avoid any duplication and simply store the predictions sorted by image number. A lighter weight version of `img_lst` could be calculated on the fly from this only for images near to the current one being displayed. The calculation should be avoided at all if the predictions checkbox is not ticked, so that the image video mode is not slowed down.

**Comment by dagewa** [comment]
Comment from @graeme-winter in #92:

> Would probably make more sense to either (i) be honest and say "I'm predicting all reflections" ideally with a button if you do not need this or (ii) {better} compute the predictions live with DIALS code i.e. when displaying the images with predictions on compute them live by holding the experiment object in memory and using the Reeke method to select reflections for prediction.
> 
> Would make the process feel much more responsive.

**Comment by dagewa** [comment]
Also from @graeme-winter, worth investigating issues with a data set like this one:
`/dls/i04/data/2018/mx22768-4/Marco/TestThaumatin/Thau_4/Thau_4_1_####.cbf`
not just BAG training data

**Comment by dagewa** [comment]
Following experience at the DLS/CCP4 workshop, I now understand that this issue is not just related to the time it takes while there is an "updating predictions" pop up progress bar displayed. There is potentially a _much longer_ time spent silently (as described in #92) before we even get to the updating predictions box.

This issue is making DUI essentially unusable for most of the datasets collected at the workshop, which are typically 1800 or 3600 0.1 deg images and often have large unit cells.

**Comment by dagewa** [comment]
`dials.predict` is now [quicker for large datasets](https://github.com/dials/dials/issues/585), which switches the focus here back to the slow navigation between nodes due to the calculation of overlays and lack of caching of this. As agreed on 11/12 this is a target for the Thailand workshop.

**Comment by luisodls** [comment]
address already
